type: default
team: acsf
service: sf-sdk-ruby

# The environment container image is used to prepare code versions
# and tooling for tests during pre, post and build stages.
environment_image:
  file: ".acquia/Dockerfile.ci"
  context: "."
  args: ""
  build_args:
    - secrets:
      - type: vault
        key: SSH_KEY
        value: GIT_SSH_KEY
        path: secret/pipeline-default/GIT_SSH_KEY
  build_matrix:
    base_images:
      - ruby:2.5
      - ruby:2.6
      - ruby:2.7

# Pre-build runs after building the environment image, and relies on it to
# run its sub-stages' steps inside of the environment container.
pre_build:
  static_analysis_lint:
    - steps:
      - bundle exec rake

# Notifications are quite noisy. Configure this once DEVOPS-620 is complete.
# notify:
#   channel: acsf-team
